### ISSUE TITLE
do not use ids for dom-elements

### ISSUE THREAD

**Issue by macrozone** [darkson95/worktime#2]
https://github.com/darkson95/worktime/blob/master/worktime.html#L60

ids have to be unique on the whole document, so you cant have multiple copies of this template on the app. I would always use classes and use ids only if is really unique to the whole app (header, footer, or unique-instances of something (timeentry-xyz)).

**Comment by macrozone** [comment]
https://github.com/darkson95/worktime/blob/master/worktime.js#L17

additionaly, you should attach the events to the template where it is used.

``````

<template name="timeButtons">
	{{#if sort}}
		<button type="button" class="btn btn-default navbar-btn btn-arrive">Kommen</button>
	{{else}}
		<button type="button" class="btn btn-default navbar-btn btn-leave">Gehen</button>
	{{/if}}
</template>


Template. timeButtons.events({
		"click .btn-arrive": function (event) {
			Meteor.call("arrive");
		},
		"click .btn-leave": function (event) {
			Meteor.call("leave");
		}
	});

**Comment by darkson95** [comment]
Thanks!
