### ISSUE TITLE
attach route-specific data to route

### ISSUE THREAD

**Issue by macrozone** [darkson95/worktime#4]
iron:router allows you to attach data and manage subscription on the router:

https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#rendering-templates-with-data
and
https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#subscriptions

so you can replace the following helper with router-data:

https://github.com/darkson95/worktime/blob/master/worktime.js#L27-L31

you can also manage the subscription on the router. It will subscribe to the data when visiting a route and will un-subscribe if user leaves the route.

This makes sense for data that are attached on the router, especially if the data of your route depend on a parameter on the route (e.g. comments/users/userxyz)

**Comment by darkson95** [comment]
Now I manage the subscriptions on the router, but i cannot render the template with data. It renders the template with one collection entry. -> I have to use findOne().

client.js:
Router.route('/', {
	subscriptions: function() {
		return Meteor.subscribe('times');
	},

	action: function () {
		if (this.ready()) {
			this.render('home', {
				data: function () {
					return Times.findOne({worker: Meteor.userId()}, {sort: {createdAt: -1}});
				}
			});
		}
		else {
			this.render('loading');
		}
	}
});

worktime.html:
<template name="home">
	<div class="container">
		{{#if currentUser}}
			<ul>
					<li><button type="button" class="btn-delete">&times;</button> - {{sort}} - {{worker}} - {{createdAt}}</li>
			</ul>
		{{else}}
			<p>Du musst eingeloggt sein!</p>
		{{/if}}
	</div>	
</template>

**Comment by macrozone** [comment]
protip: use \`\`\` for code in github-markdown ;-)

\`\`\`
my code
\`\`\`

looks like this:
```
my Code
```

**Comment by macrozone** [comment]
why dont you use Times.find(...) ?

**Comment by macrozone** [comment]
btw. I usually use iron router like this:

```
Router.route('/', {
  template: "home",
  subscriptions: function() {
    return Meteor.subscribe('times');
  },
  data: function() {
    return Times.find({worker: Meteor.userId()}, {sort: {createdAt: -1}});
  }
});
```

if you specify a loadingTemplate (can be defined globally or on one route) and use use `waitOn` instead of `subscriptions`, you can omit `if (this.ready()) {...}`. See https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#the-waiton-option

**Comment by darkson95** [comment]
I edited the files and it doesn't work. 
client.js
```
Router.route('/', {
	loadingTemplate: "loading",
	template: "home",
	waitOn: function() {
		return Meteor.subscribe('times');
	},
	data: function() {
		return Times.find({worker: Meteor.userId()}, {sort: {createdAt: -1}});
	}
});
```

worktime.html
```
<template name="home">
	<div class="container">
		{{#if currentUser}}
			<ul>
				{{#each data}}
					<li><button type="button" class="btn-delete">&times;</button> - {{sort}} - {{createdAt}} - {{hoursWorked}}</li>
				{{/each}}
			</ul>
		{{else}}
			<p>Du musst eingeloggt sein!</p>
		{{/if}}
	</div>	
</template> <!-- Mainpage -->
```

**Comment by macrozone** [comment]
`data` in ironrouter sets the context for the template itself. In Spacebars (the template-language) you can refere to the context itself with "this" or ".".

So you have two options:

```
data: function() {
  return Times.find({worker: Meteor.userId()}, {sort: {createdAt: -1}});
}

{{#each this}}
   ...
{{/each}}

```

or

```
data: {
  times: function() {
    return Times.find({worker: Meteor.userId()}, {sort: {createdAt: -1}});
  }
}

{{#each times}}
   ...
{{/each}}

```

btw: you're welcome :-D
