### ISSUE TITLE
use autform / quickform / simpleschema

### ISSUE THREAD

**Issue by macrozone** [darkson95/worktime#5]
there are nice community packages that can create & validate forms based on a schema:

https://github.com/aldeed/meteor-autoform

you can replace this lines here https://github.com/darkson95/worktime/blob/master/worktime.html#L55-L57 with a quickForm-tag. 

it is also used in a nice admin-package: https://github.com/yogiben/meteor-admin

**Comment by darkson95** [comment]
It is possible, that I can set the value in Wages.attachSchema? Because I want to set the value of "createdAt" like this:

Wages.attachSchema(new SimpleSchema({
	wage: {
		type: String,
		label: "neuer Stundenlohn"
	},
	createdAt: {
		type: Date,
		label: "gültig ab",
		value: new Date()
	}
}));

**Comment by macrozone** [comment]
checkout https://github.com/aldeed/meteor-simple-schema#autovalue

2015-04-27 22:25 GMT+02:00 darkson95 <notifications@github.com>:

**Comment by darkson95** [comment]
Thanks! :)
